services:
  postgres:
    image: postgres:16-alpine
    container_name: event-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  event-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: event-service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    ports:
      - '3002:3000'
    networks:
      - app_network
    command: sh -c "pnpm prisma migrate deploy && pnpm run start:prod"

volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
